### ISSUE TITLE
Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by lasseborly** [Schmavery/facebook-chat-api#110]
```
ERR! ERROR in listen -->  TypeError: Cannot read property 'toString' of undefined
ERR! ERROR in listen -->      at Object.formatTyp (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/utils.js:294:23)
ERR! ERROR in listen -->      at parsePackets (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/src/listen.js:97:42)
ERR! ERROR in listen -->      at Array.forEach (native)
ERR! ERROR in listen -->      at /home/pc/Desktop/fbbot/node_modules/facebook-chat-api/src/listen.js:86:12
ERR! ERROR in listen -->      at tryCatcher (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/util.js:26:23)
ERR! ERROR in listen -->      at Promise._settlePromiseFromHandler (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:507:31)
ERR! ERROR in listen -->      at Promise._settlePromiseAt (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:581:18)
ERR! ERROR in listen -->      at Promise._settlePromises (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/promise.js:697:14)
ERR! ERROR in listen -->      at Async._drainQueue (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:123:16)
ERR! ERROR in listen -->      at Async._drainQueues (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:133:10)
ERR! ERROR in listen -->      at Immediate.Async.drainQueues [as _onImmediate] (/home/pc/Desktop/fbbot/node_modules/facebook-chat-api/node_modules/bluebird/js/main/async.js:15:14)
ERR! ERROR in listen -->      at processImmediate [as _immediateCallback] (timers.js:383:17)
```

I'm getting this error by doing something rather trivial. Is it me being totally off point or what is happening here?

```javascript
var login = require("facebook-chat-api");

var person02ID = 00000000;
var person01ID = 00000000;

var testreg = /(test)/ig;

login({email: "FB_EMAIL", password: "FB_PASS"}, function callback (err, api) {
    if(err) return console.error(err);

    api.setOptions({
        listenEvents: true,
        selfListen: true
    });


    var stopListening = api.listen(function(err, event) {
        if(err) return console.error(err);

        if (typeof event !== "undefined") {

            switch(event.type) {
                case "message":

                    //Stop
                    if(event.body === '/stop') {
                        api.sendMessage("Goodbye...", event.threadID);
                        return stopListening();
                    }

                    //Person01
                    if (event.senderID == person01ID) {
                        if (testreg.test(event.body)) {
                            api.sendMessage('Hi...', event.threadID);
                        }
                    }

                    //Person02
                    if (event.senderID == person02ID) {
                        if (testreg.test(event.body)) {
                            api.message('Hey u...', event.threadID);
                        }
                    }


                    break;

                case "event":
                    console.log(event);
                    break;
            }

        }


    });
});

```

I'm sorry if this issue is same as [this](https://github.com/Schmavery/facebook-chat-api/issues/89) but a solution was not to be found from that issue.

**Comment by bsansouci** [comment]
Hey @lasseborly, that does seem like #89. Can you print `event` right above [this line](https://github.com/Schmavery/facebook-chat-api/blob/f9be7a15738003cc185ed3dae5a21193d9dec59d/utils.js#L291) and give us the output?

**Comment by Schmavery** [comment]
As far as I understood #89 had a non-null `err` and was very intermittent, so they could potentially be different issues.  Regardless, it would be nice see the result of @bsansouci's suggestion.

@bsansouci I would like if we could start logging things like this all the time under a `verbose` mode that can be enabled in the start options.  Having proper logs would make these issues easier to debug.

**Comment by bsansouci** [comment]
@Schmavery I'm ok with verbose logging

**Comment by blazeu** [comment]
This happens whenever ``typ`` event is received

**Comment by Schmavery** [comment]
We've had some issues in the past of facebook serving different version of the typ event to different people, making it difficult to debug.  If someone who is experiencing this problem could post the result of @bsansouci's instructions above and print out the original typ event, that would be extremely helpful.

**Comment by blazeu** [comment]
Apparently this is fixed in commit 4d3619d80f78ac8540bb42443d3e7c6d044764f7, but it's not on npm

**Comment by Schmavery** [comment]
I'll publish when I get home, having not done so because it was never confirmed that 4d3619d actually solved #100.
It would be nice if @lasseborly could confirm that the most recent version of the repo is fixing his problem.

**Comment by Schmavery** [comment]
The newest changes are now on npm.
@lasseborly can you update to v1.0.4 (latest) and confirm it is working?

**Comment by lasseborly** [comment]
Sorry for the late update. I have updated to the newest version (1.0.4) and printing event right before [this line](https://github.com/Schmavery/facebook-chat-api/blob/f9be7a15738003cc185ed3dae5a21193d9dec59d/utils.js#L291) returns me `{ type: 'typ', from: 590007219, st: 1 }`  and the same errors occurs. 

So unfortunately no @Schmavery, the update did not solve it for some reason.

**Comment by Schmavery** [comment]
Ok thanks for the update.  Looks like I was right and facebook might be serving a couple of different versions of this endpoint (though as @bsansouci pointed out, our tests don't actually cover this right now).
Is there any chance that you can confirm that this only happens in a 1-on-1 chat or whether it also happens in a group chat? (3+ people).  If you get the same error in a group chat, can you show us the event for that as well?

**Comment by Schmavery** [comment]
Hey @lasseborly, I just went with my hunch and made a change that should fix your issue.  Can you update to the latest github version (haven't pushed to npm yet) and verify that it works?

**Comment by Schmavery** [comment]
I'm going to close this assuming it worked.  Please reopen if you have a problem.

**Comment by bearbear12345** [comment]
Hi, I'm also getting this issue on v1.0.4

https://github.com/Schmavery/facebook-chat-api/issues/89#issuecomment-167988809

**Comment by bearbear12345** [comment]
^ Looks like some typing events don't have all the information.

To be honest, I don't think many users need the typing event, maybe add an option to not listen to those events? / ignore them?

**Comment by bearbear12345** [comment]
Ideally you could edit **facebook-chat-api/src/listen.js**, removing lines 107 to 112, leaving just the break.

Temporary solution - I ended up just overriding the **formatTyp** function in my script to remove the other keys that don't always appear
```
  /* #module overrides */
  require('facebook-chat-api/utils').formatTyp = function(event) {
    return {
      isTyping: !!event.st,
      from: event.from.toString(),
      /* threadID: (event.to || event.thread_fbid || event.from).toString(),
      from_mobile: !!event.from_mobile,
      userID: (event.realtime_viewer_fbid || event.from).toString(), */
      // ^ In some typing event instances, the above three keys aren't received, causing errors
      type: 'typ',
    };
  }
```

Would be better if it could just not be called at all, but overriding the whole listen function isn't going to work well

**Comment by bsansouci** [comment]
```js
/* #module overrides */
  require('facebook-chat-api/utils').formatTyp = function(event) {
    return {
      isTyping: !!event.st,
      from: event.from.toString(),
      threadID: (event.to || event.thread_fbid || event.from).toString(),
      from_mobile: !!event.from_mobile,
      userID: (event.realtime_viewer_fbid || event.from).toString(),
      // ^ In some typing event instances, the above three keys aren't received, causing errors
      type: 'typ',
    };
  }
```
Please try it like this.  I don't understand why this wouldn't work given the events you showed us.

**Comment by bsansouci** [comment]
Also as @Schmavery said, this code isn't pushed to npm repo yet, so v1.0.4 isn't what you want.  If you want to actually check if this works, please update to the latest github version (aka please clone the master branch) as mentioned, otherwise you may have issues with other fixed bugs.

**Comment by bearbear12345** [comment]
I wrote some of the event outputs in the comments of 2059829317ed40d0c46872ddea763e05c441d4af

**Comment by Schmavery** [comment]
We saw those events and there should be no reason that they wouldn't be handled by the latest code.  Please test again using the above instructions.

**Comment by Schmavery** [comment]
I'm going to close this for now.  If you run into problems please open a new issue.
