### ISSUE TITLE
Echo bot not working

### ISSUE THREAD

**Issue by valentinsabbath** [Schmavery/facebook-chat-api#243]
Echo Bot not making eco  and non stop when you send '/stop'

**Comment by Schmavery** [comment]
Please include more details.  What version are you using?  This will probably be fixed by v2.0

**Comment by Damp-Cuttlefish** [comment]
Same problem here using the latest version from npm. 
The example echo bot and my own code that used to work both stopped working a few days ago, now the only events api.listen receives are typing notifications. Setting logLevel to verbose shows that it's still receiving messages and other notifications, so I assume the message format has changed.

**Comment by jboby93** [comment]
I believe I'm having the same issue as OP,  I added a few logging statements to detect when the callback is being triggered, and it's apparently not getting triggered at all for "message"-type events; it seems to be responding though when event.type === "event" or anything else except for "message" because it acknowledges them in the console.  For messages, it just prints "got answer" and does nothing else.

i tried it on both node.js v4.4.2 and v5.10.1, and am using the latest release of facebook-chat-api (1.0.8).

![screenshot_194](https://cloud.githubusercontent.com/assets/7563505/14344657/ec1d9466-fc76-11e5-985e-db2f7853d6da.png)

**Comment by ErmanSayin** [comment]
You can do `npm install Schmavery/facebook-chat-api` to get the latest git version

**Comment by jboby93** [comment]
I read through that thread, and your comment there fixed the issue for me.  Thanks!

> cd node_modules
> rm -rf facebook-chat-api
> ​git clone http://github.com/Schmavery/facebook-chat-api.git
> cd ​facebook-chat-api
> npm update

**Comment by valentinsabbath** [comment]
Thank guys! @jboby93 instructions worked for me :+1:

**Comment by Schmavery** [comment]
Sorry for the confusion everyone, these fixes will be pushed to npm this weekend.  We wanted to take a couple days to make sure they didn't introduce any new bugs first.  Glad you figured it out :)
